### ISSUE TITLE
Debugging helpers for camera, axis etc

### ISSUE THREAD

**Issue by oal** [azul3d/gfx#91]
There should be a debugging package that can generate meshes for the camera frustum, axis, arrows etc.

Examples:

* http://threejs.org/examples/#webgl_camera
* http://threejs.org/examples/#webgl_helpers

**Comment by slimsag** [comment]
Thank you for creating this. I agree that we should add some visual debugging features.

This would fit well into a `azul3d.org/gfx.v2/debug` package.

**Comment by oal** [comment]
I was poking around a little after I created this issue, and for a camera helper, it'd be nice to have .Near(), .Far() and .Fov() (.FOV or .FieldOfView) on the gfx.Camera struct, so that the helper can be created after the camera perspective is set. Now it's just used for the transformation matrix, right?

Then the camera frustum helper could just read those values on the camera it's connected to, and update its vertices.

Or do you have any other suggestions?

**Comment by slimsag** [comment]
As of right now `gfx.Camera` is primarily just two components: a `gfx.Object` and a `gfx.Mat4` projection matrix.

`Near` `Far` and `FOV` methods sound like good ideas to me, but we should be clear about what `FOV` returns for an orthographic camera, though (`-1`, `0` etc?).

The `gfx.Camera.Object` should be used to represent the visible portion of the camera, such that at some point a call to:

```
canvas.Draw(rect, cam.Object, cam2)
```

Would need be made. (`cam2` is effectively the camera _viewing_ the debug camera -- or `nil` for none).

Perhaps the best cleanest approach would be something like:

```
// DrawCamera draws the camera's viewing frustum to the canvas as a wire-frame.
func DrawCamera(c gfx.Canvas, cam gfx.Camera) {
    ....
    // TODO: assign a shader and mesh with vertices to cam.Object.
    ....
}
```

We need not worry about performance for the initial impl, since it is primarily for debugging. In practice it would work like:

```
// Debug draw myCamera to myCanvas:
debug.DrawCamera(myCanvas, myCamera)
```

**Comment by oal** [comment]
Ok, sounds good. I forked the repo and added the methods to the camera. Does that look OK, and do you want me to open a pull request for that? I'm not that experienced when it comes to contributing to other projects using git and Github.

I'll try to start working on the camera helper too.

**Comment by slimsag** [comment]
That looks good. Please send a PR for your change.

Also see http://azul3d.org/doc/contributing.html#attribution

**Comment by oal** [comment]
The camera helper in my fork seems to work correctly now. I also wanted to add an example to the examples repo, but I can't seem to find a way to render to two windows at the same time.
